### ISSUE TITLE
CSGOFloat not working

### ISSUE THREAD

**Issue by atdevilx** [csfloat/extension#163]
on chrome thew error CSGOFloat TypeError: Failed to fetch appears and on firefox the error Unknown Error.
It has worked for me before in chrome but now its not

**Comment by hy3pp** [comment]
same shit happening to me

**Comment by Step7750** [comment]
Don't use a VPN.

**Comment by hy3pp** [comment]
im not using a vpn?

**Comment by atdevilx** [comment]
A program i used was acting kinda like a VPN that was the problem.
