### ISSUE TITLE
Incompatibility With VPN Usauge 

### ISSUE THREAD

**Issue by chasereid99** [csfloat/extension#171]
HI, it appears to not work while using a VPN,  the only way to get around the soft ban, that reads: Sorry!
An error was encountered while processing your request:

You've made too many requests recently. Please wait and try your request again later.

While using the VPN to get around that issue, the CSFloat tracker displays: CSFloat TypeError: Failed to fetch. On all items and from the website it displays no items found, but when disabling the VPN website now displays all items for sale.

**Comment by Step7750** [comment]
This is intentional, don't use a VPN.
