### ISSUE TITLE
Cant enable offer tracking

### ISSUE THREAD

**Issue by Yahmice** [csfloat/extension#219]
"Click enable for "Setup Offer Tracking on CSFloat" in the banner." Problem is, when I press "enable" I see a message: "failed to obtain permissions"

Version of csfloatchecker: 4.1.2

**Comment by Yahmice** [comment]
> Which browser environment are you on?

I tried opera at first, thought problem was on the browser, so I switched to google chrome, but it didn't solve the problem

**Comment by Yahmice** [comment]
> Are you logged into CSFloat in the same session? Does Edge have the same issue?

Yes, I was logged. Don't know about edge, don't use him on my pc

**Comment by cardealpt** [comment]
it doesnt recognize the plugin installed on chrome. cant sell items

**Comment by sez76** [comment]
hello, same problem with csfloatchecker: 4.3.1

**Comment by Step7750** [comment]
There is no issue that is reproducible for this -- make sure you're clicking on "Allow" since it isn't the default solid-blue button.
