### ISSUE TITLE
Bug : Error to fetch items in steam market

### ISSUE THREAD

**Issue by ZlejKrysak** [csfloat/extension#231]
Hello, i wanted to check floats on steam market and its not working since 15pm. At morning it works perfectly but now not. I tried to reinstalling the extension for chrome even remove other extensions for steam market still doesn't work. this is the message that sends me under the skin - CSFloat TypeError: Failed to fetch

![bug](https://github.com/csfloat/extension/assets/169307946/6407f61f-04ae-44bd-ae25-d27d75760262)

**Comment by Step7750** [comment]
If you're using a VPN, disable it.

This is a localized issue.
