### ISSUE TITLE
CSFloat Market Checker

### ISSUE THREAD

**Issue by therealriley** [csfloat/extension#240]
I had to reinstall the new one, and when i go to install it it just buffers forever

**Comment by Step7750** [comment]
You're going to have to be much more specific about what you're seeing.

What error? What does "buffers forever" mean? What browser?

**Comment by therealriley** [comment]
https://gyazo.com/fa47354be7742f86a7dd1d3e100496e0

Im using updated chrome, when i go to install the extension it never installs

**Comment by therealriley** [comment]
![notworking](https://github.com/csfloat/extension/assets/5239347/4789b529-74d4-4403-bba9-0e7f8c6b003d)

**Comment by Step7750** [comment]
This looks like a bug in Chrome Web Store -- trying to add any extension at the moment infinitely loads.

You'll need to wait for Google to resolve it.
