### ISSUE TITLE
Fixed 

### ISSUE THREAD

**Issue by ghost** [csfloat/extension#245]
Hello,
I'm trying to buy floats with my birthday values; however, whether I'm trying to find one, it takes ages to go through all of the pages for each skin. Could you please tell me if there's a way to make the extension show more than 100 listings on one page or, even better, when the float filter is used, hide the listings that didn't meet the requirements and show only the ones that met. I will be very thankfully for your help^^

**Comment by Oreoezi** [comment]
Please close the issue instead of renaming it to "Fixed".
