### ISSUE TITLE
CSFLoat extension site permission issues

### ISSUE THREAD

**Issue by BreakLime** [csfloat/extension#246]
I get the following warning message in the trading menu on csfloat.

![image](https://github.com/user-attachments/assets/668808fe-d607-49c6-97cf-fde6b302407d)

The thing is the csfloat extension  is installed with the correct permissions.

![image](https://github.com/user-attachments/assets/96d323e0-22c7-4206-8b6a-6691c4d97809)

Google Chrome Version 127.0.6533.89
CSFloat Market Checker Version 4.3.1

**Comment by Step7750** [comment]
There are improved error messages and handling for this scenario on the site.
