### ISSUE TITLE
Can't see float numbers in Firefox 129.0.2 (64-bit)

### ISSUE THREAD

**Issue by TC76** [csfloat/extension#249]
For a bit of context, i had the version from the firefox addon website (which is 3.3.1) for a good while now, like more than 1 year, and it was working fine before.
I saw on the github there was a newer version (4.3.1), and i tried disabling the one already installed, and installing it as a temporary add-on, but saw that it didn't load float numbers, so i deleted it, and tried to go back to 3.3.1 that i already had installed, and now this one won't show float numbers either. it shows "Loading..." on Market posts, and shows nothing on inventory icons (shows "Loading..." when clicking a weapon for details on the right).
![infinite loading](https://github.com/user-attachments/assets/66455b45-60f5-41d5-b61f-6f8923788f09)

![inventory](https://github.com/user-attachments/assets/f500c606-e321-4f14-8294-75f68df6b1d6)

I have tried fully removing it (both from the addon website, and firefox addon settings page), restarted both firefox and my computer, as well as deleting cache hoping it works again, but it just doesn't. As stated, i'm on Firefox 129.0.2 64-bit.

**Comment by GrexVibra** [comment]
is the problem solved?
mine still stuck on loading. :(
