### ISSUE TITLE
Trades Cancel if Trade isnt confirmed within short period of time

### ISSUE THREAD

**Issue by jkroyce** [csfloat/extension#257]
The recent PR that added canceling of trades has been prematurely canceling trades offers. This cancelation of the trade offer then cancels the trade offer on the site causing the seller to be at fault. The site says that it allows for up to 18 hours to accept a confirmation, but if the confirmation is not accepted in an hour the trade is canceled and the seller is put at fault.

**Comment by Step7750** [comment]
No, this is intentional. You are supposed to confirm the trade offer _immediately_ after creating it.

You are not meant to be granted 18 hours to confirm it, however that time frame was granted before due to early-issues of sellers ignorantly confirming trade offers well after sales had failed.
