### ISSUE TITLE
CSFloat Extension Not Working on Firefox

### ISSUE THREAD

**Issue by GrexVibra** [csfloat/extension#258]
stuck on loading.
![Capture](https://github.com/user-attachments/assets/ab1adf19-d1ae-4f87-b1f7-68ec563a6090)

tried uninstall/install both extension and firefox multiple times, still same.
w10, firefox updated.
kindly help.

**Comment by mrchilliballs** [comment]
Same issue on firefox 128

**Comment by Step7750** [comment]
Duplicate of https://github.com/csfloat/extension/issues/249
